server:
  global_server_ip: "0.0.0.0"
  grpc_port: 8082
  http_port: 8000
database:
  type: sqlite
  path: "../db/cameras.db"

log:
  path: "../logs/app.log"
  level: "info"

ffmpeg:
  stream_port_range:
    min: 8090
    max: 8099