syntax = "proto3";

package gymvision;

// Определяем сервис
service LocalServer {
  rpc StartStream (CameraInfo) returns (StreamInfo);
  rpc StartStreamCV (CameraInfo) returns (StreamInfo);
  rpc MoveCamera (RotateInfo) returns (Response);
  rpc StopMove (CameraInfo) returns (Response);
}

// Определяем сообщения
message CameraInfo {
  int32 camera_id = 1;
}

message RotateInfo {
  int32 camera_id = 1;
  float rotate_x = 2;
  float rotate_y = 3;
}

message StreamInfo {
  string stream_url = 1;
}

message Response {
  string msg = 1;
}